name: Simple Log Test

on:
  push:
    branches: [ master ]  # master branch এ push হলে trigger হবে

jobs:
  log-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print a log message
      run: echo "GitHub Actions triggered successfully!"
