name: Simple Log Test

on:
  push:
    branches: [ master ]  # master branch এ push হলে trigger হবে

jobs:
  log-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Print a log message
      run: echo "GitHub Actions triggered successfully!"

    - name: Print multiple log messages
      run: |
        echo "GitHub Actions triggered successfully!"
        echo "Branch: ${{ github.ref_name }}"
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "Workflow is running on Ubuntu"
    - name: successfully completed
      run: echo "GitHub Actions completed successfully!"

